FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# LootSafe Interface API

Interface with the blockchain smart contracts and manage your game assets

## Meta [/v1/]

Get metadata about the api

### Get API Metadata [GET]

+ Response 200 (application/json)

        {
          "name": "blockbench.api",
          "version": "1.0.0",
          "author": "wski",
          "license": "UNLICENSED",
          "uptime(ms)": 703155,
          "ethereum": {
            "account": "0x627306090abab3a6e1400e9345bc60c78a8bef57",
            "testnet": true,
            "chain": "testrpc",
            "provider": "http://localhost:8545"
          },
          "contracts": {
            "StandardToken": "0x345ca3e014aaf5dca488057592ee47305d9b3e10",
            "Item": "0xf25186b5081ff5ce73482ad761db0eb0d25abfbf",
            "Meta": "0x8f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f",
            "LootBox": "0x2c2b9c9a4a25e24b174f26114e8926a9f2128fe4",
            "BlockBench": "0x30753e4a8aad7f8597332e813735def5dd395028",
            "CoreToken": "0xfb88de099e13c3ed21f80a7a1e49f8caecf10df6"
          }
        }

## Group Crafting


## List Craftable Items [/v1/craftables]

Get a list of craftable items

### Craftables [GET]

+ Response 200 (application/json)

        {
            "status": 200,
            "message": "Craftables fetched",
            "data": [
                "0xc0c5def23634cfeb9f108b51371831e396e0eb90"
            ]
        }


## Create Recipie [/v1/recipie/new]

Create a new recipie

### Create a Recipie [POST]

+ Request (application/json)

    + Headers
        
            key: pWpzWuxoKUKAmlHc0wPi7lFS38FTth
            otp: ccccccglcrcdfbvrelclvcgjbbkkjtkhcvdbnlljlgke
    
    + Body

            {
                "result": "0x0",
                "materials": [
                    "0x01",
                    "0x02",
                    "0x03"
                ],
                "counts": [
                    2,
                    5
                    3
                ]
            }


+ Response 200 (application/json)

    + Body


            {
                "status": 200,
                "message": "New recipie added",
                "data": {
                    "tx": "0x457e33bc1f00203e1b4c538324bc55da66a56fcbab1398c90262fddd4ecd9447",
                    "receipt": {
                        "transactionHash": "0x457e33bc1f00203e1b4c538324bc55da66a56fcbab1398c90262fddd4ecd9447",
                        "transactionIndex": 0,
                        "blockHash": "0x230cfe96ff2ab0efb562376527b4653d7b90fee1471b9e7f0517c362211f820c",
                        "blockNumber": 11,
                        "gasUsed": 211351,
                        "cumulativeGasUsed": 211351,
                        "contractAddress": null,
                        "logs": [],
                        "status": 1
                    },
                    "logs": []
                }
            }
    


## Remove Recipie [/v1/recipie/remove]

Remove a recipie

### Remove a Recipie [POST]

+ Request (application/json)

    + Headers
        
            key: pWpzWuxoKUKAmlHc0wPi7lFS38FTth
            otp: ccccccglcrcdfbvrelclvcgjbbkkjtkhcvdbnlljlgke
    
    + Body

            {
                "item": "0x0"
            }


+ Response 200 (application/json)

    + Body

            {
                "status": 200,
                "message": "Recipie removed",
                "data": {
                    "tx": "0x0c0d5348e45983246e1dbe93af39bfc6fb965472b176c9959658f57133643ac7",
                    "receipt": {
                        "transactionHash": "0x0c0d5348e45983246e1dbe93af39bfc6fb965472b176c9959658f57133643ac7",
                        "transactionIndex": 0,
                        "blockHash": "0x5ea70479e604641dd0fe0e45fce7db5b987554e4f9bbf6d6c0e3882c8f5fca14",
                        "blockNumber": 17,
                        "gasUsed": 30242,
                        "cumulativeGasUsed": 30242,
                        "contractAddress": null,
                        "logs": [],
                        "status": 1
                    },
                    "logs": []
                }
            }


## List Craftable Items [/v1/recipie/get/0x0]

Get a recipie

### Get Recipie [GET]

+ Response 200 (application/json)

        {
            "status": 200,
            "message": "Item fetched",
            "data": [
                [
                    "0x8867a31f7f3f240fb82468ab109f732fe21fcd38",
                    "0xda1ddf7553daa5cb18d2ff0823d1609d4858cfc3"
                ],
                [
                    "2",
                    "1"
                ]
            ]
        }

## Group Items

## List Items [/v1/item/list]

Get a list of the uint8 names of items in the system

### List Items [GET]

+ Response 200 (application/json)

        {
            "status": 200,
            "message": "Items fetched",
            "items": [
                "0x536869656c640000",
                "0x00000f0000000000"
            ],
            "decoded": [
                "Shield",
                ""
            ]
        }
        
## List Ledger [/v1/item/ledger]

Get a list of the items, and data from items

### List Ledger [GET]

+ Response 200 (application/json)

         
        
        {
            "status": 200,
            "message": "Items fetched",
            "data": [
                {
                    "address": "0x84b0a9e566b73277692707852c01018c11c62a7d",
                    "id": "0x736869656c640000000000000000000000000000000000000000000000000000",
                    "skin": "0x64656661756c7400000000000000000000000000000000000000000000000000",
                    "metadata": "no_metadata",
                    "created": "1513656396",
                    "owner": "0x5759fbaf72597c61f0e44c499896efe34b46871f",
                    "symbol": "0x5341564500000000",
                    "totalSupply": "120000",
                    "finalSupply": "1",
                    "vault": "0"
                },
                {
                    "address": "0x994d3972bfba7c22be9eafc996e46bffea084102",
                    "id": "0x73776f7264000000000000000000000000000000000000000000000000000000",
                    "skin": "0x64656661756c7400000000000000000000000000000000000000000000000000",
                    "metadata": "no_metadata",
                    "created": "1513656876",
                    "owner": "0x5759fbaf72597c61f0e44c499896efe34b46871f",
                    "symbol": "0x5341564500000000",
                    "totalSupply": "120000",
                    "finalSupply": "0",
                    "vault": "0"
                }
            ]
        }

## Get Item [/v1/item/get/Shield]

Get a specific items address

### Get Item [GET]

+ Response 200 (application/json)

        {
            "status": 200,
            "message": "Item fetched",
            "itemResponse": "0xc0c5def23634cfeb9f108b51371831e396e0eb90"
        }
  
## Get Token Address [/v1/address/token]

Get the address of the token contract

### Get Token Address [GET]

+ Response 200 (application/json)

        {
            "status": 200,
            "tokenAddress": "0x6b5f2b72ed649a5018701eb2b71c4fd8f472595c"
        }
 
 
## New Item [/v1/item/new]

Create a new item on the network

### Create a New Item [POST]

+ Request (application/json)

    + Headers
        
            key: pWpzWuxoKUKAmlHc0wPi7lFS38FTth
            otp: ccccccglcrcdfbvrelclvcgjbbkkjtkhcvdbnlljlgke
    
    + Body

            {
                "name": "0x00000f",
                "id": "shield",
                "totalSupply": 120000
            }


+ Response 200 (application/json)

    + Body
      
            {
                "status": 200,
                "message": "Created new item",
                "data": {
                    "tx": "0xb821ce36f9a38d74e10e5b0a2579b0843862e7e3e4265d55f8b7637110fc0717",
                    "receipt": {
                        "transactionHash": "0xb821ce36f9a38d74e10e5b0a2579b0843862e7e3e4265d55f8b7637110fc0717",
                        "transactionIndex": 0,
                        "blockHash": "0xca21919fd1b8e87913db669070ff2b790dbc9939204be202ddca022ed531ccca",
                        "blockNumber": 12,
                        "gasUsed": 760586,
                        "cumulativeGasUsed": 760586,
                        "contractAddress": null,
                        "logs": [
                            {
                                "logIndex": 0,
                                "transactionIndex": 0,
                                "transactionHash": "0xb821ce36f9a38d74e10e5b0a2579b0843862e7e3e4265d55f8b7637110fc0717",
                                "blockHash": "0xca21919fd1b8e87913db669070ff2b790dbc9939204be202ddca022ed531ccca",
                                "blockNumber": 12,
                                "address": "0x30753e4a8aad7f8597332e813735def5dd395028",
                                "data": "0x000000000000000000000000c0c5def23634cfeb9f108b51371831e396e0eb90",
                                "topics": [
                                    "0xc84c1949c25c3720439bdbb249aef7fe95085fe4af1820022b566cd94d671848"
                                ],
                                "type": "mined"
                            }
                        ],
                        "status": 1
                    },
                    "logs": [
                        {
                            "logIndex": 0,
                            "transactionIndex": 0,
                            "transactionHash": "0xb821ce36f9a38d74e10e5b0a2579b0843862e7e3e4265d55f8b7637110fc0717",
                            "blockHash": "0xca21919fd1b8e87913db669070ff2b790dbc9939204be202ddca022ed531ccca",
                            "blockNumber": 12,
                            "address": "0x30753e4a8aad7f8597332e813735def5dd395028",
                            "type": "mined",
                            "event": "ItemCreated",
                            "args": {
                                "itemAddress": "0xc0c5def23634cfeb9f108b51371831e396e0eb90"
                            }
                        }
                    ]
                }
            }

## Spawn Item [/v1/item/spawn]

Give an address one item

### Spawn a New Item [POST]

+ Request (application/json)

    + Headers
        
            key: pWpzWuxoKUKAmlHc0wPi7lFS38FTth
            otp: ccccccglcrcdfbvrelclvcgjbbkkjtkhcvdbnlljlgke
    
    + Body

            {
                "itemAddress": "0x00000000000000000000000000",
                "to": "0x1337c0de2ce6f6f75044ebaf22449db048faec5d",
            }


+ Response 200 (application/json)

    + Body
      
            {
                "status": 404,
                "message": "Spawned one item",
                "tx": {
                    "tx": "0x066df249f112bc91a6b7ddf842c2b68e216be881ff3ae9b532ac9cce28c51798",
                    "receipt": {
                        "transactionHash": "0x066df249f112bc91a6b7ddf842c2b68e216be881ff3ae9b532ac9cce28c51798",
                        "transactionIndex": 0,
                        "blockHash": "0xcf002aebf442fb62dcd6786e1f62f0bd7f91b96b53422223208ea96c64cae75d",
                        "blockNumber": 25,
                        "gasUsed": 56931,
                        "cumulativeGasUsed": 56931,
                        "contractAddress": null,
                        "logs": [
                            {
                                "logIndex": 0,
                                "transactionIndex": 0,
                                "transactionHash": "0x066df249f112bc91a6b7ddf842c2b68e216be881ff3ae9b532ac9cce28c51798",
                                "blockHash": "0xcf002aebf442fb62dcd6786e1f62f0bd7f91b96b53422223208ea96c64cae75d",
                                "blockNumber": 25,
                                "address": "0x30753e4a8aad7f8597332e813735def5dd395028",
                                "data": "0x000000000000000000000000da1ddf7553daa5cb18d2ff0823d1609d4858cfc348656c6d000000000000000000000000000000000000000000000000000000000000000000000000000000001337c0de2ce6f6f75044ebaf22449db048faec5d",
                                "topics": [
                                    "0x93716d6e5a45e207f04d5c28cab80dff479b9fe92f341212be47969cb084e4c6"
                                ],
                                "type": "mined"
                            },
                            {
                                "logIndex": 1,
                                "transactionIndex": 0,
                                "transactionHash": "0x066df249f112bc91a6b7ddf842c2b68e216be881ff3ae9b532ac9cce28c51798",
                                "blockHash": "0xcf002aebf442fb62dcd6786e1f62f0bd7f91b96b53422223208ea96c64cae75d",
                                "blockNumber": 25,
                                "address": "0xda1ddf7553daa5cb18d2ff0823d1609d4858cfc3",
                                "data": "0x0000000000000000000000000000000000000000000000000000000000000001",
                                "topics": [
                                    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                                    "0x00000000000000000000000030753e4a8aad7f8597332e813735def5dd395028",
                                    "0x0000000000000000000000001337c0de2ce6f6f75044ebaf22449db048faec5d"
                                ],
                                "type": "mined"
                            }
                        ],
                        "status": 1
                    },
                    "logs": [
                        {
                            "logIndex": 0,
                            "transactionIndex": 0,
                            "transactionHash": "0x066df249f112bc91a6b7ddf842c2b68e216be881ff3ae9b532ac9cce28c51798",
                            "blockHash": "0xcf002aebf442fb62dcd6786e1f62f0bd7f91b96b53422223208ea96c64cae75d",
                            "blockNumber": 25,
                            "address": "0x30753e4a8aad7f8597332e813735def5dd395028",
                            "type": "mined",
                            "event": "ItemSpawned",
                            "args": {
                                "itemAddress": "0xda1ddf7553daa5cb18d2ff0823d1609d4858cfc3",
                                "name": "0x48656c6d000000000000000000000000",
                                "to": "0x1337c0de2ce6f6f75044ebaf22449db048faec5d"
                            }
                        }
                    ]
                }
            }
      
     
## Clear Availability of Item [/v1/item/clearAvailability]

Clear remaining un-distrobuted supply of item

### Cler Availability [POST]

+ Request (application/json)

    + Headers
        
            key: pWpzWuxoKUKAmlHc0wPi7lFS38FTth
            otp: ccccccglcrcdfbvrelclvcgjbbkkjtkhcvdbnlljlgke
    
    + Body

            {
                "itemAddress": "0x0"
            }


+ Response 200 (application/json)

    + Body
    
            {
                "status": 404,
                "message": "Cleared available supply of item",
                "tx": {
                    "tx": "0x9ce67ba6f90a7017e3cf425fb3c76b7eec353e7908c089cbccdcd22ec89b3036",
                    "receipt": {
                        "transactionHash": "0x9ce67ba6f90a7017e3cf425fb3c76b7eec353e7908c089cbccdcd22ec89b3036",
                        "transactionIndex": 0,
                        "blockHash": "0x4f55beca03cb5ce8964e09adc1ba064392a62152687f98d79cb7960d2d6dde87",
                        "blockNumber": 20,
                        "gasUsed": 38457,
                        "cumulativeGasUsed": 38457,
                        "contractAddress": null,
                        "logs": [
                            {
                                "logIndex": 0,
                                "transactionIndex": 0,
                                "transactionHash": "0x9ce67ba6f90a7017e3cf425fb3c76b7eec353e7908c089cbccdcd22ec89b3036",
                                "blockHash": "0x4f55beca03cb5ce8964e09adc1ba064392a62152687f98d79cb7960d2d6dde87",
                                "blockNumber": 20,
                                "address": "0xf204a4ef082f5c04bb89f7d5e6568b796096735a",
                                "data": "0x00000000000000000000000010271f4b537610009e1daf06779b9a8fde5ff531536869656c640000000000000000000000000000000000000000000000000000",
                                "topics": [
                                    "0x69d728a8bb5d6c7b351c35e1d8070b54ab2084f5d72bdb3a1782493a492b2e58"
                                ],
                                "type": "mined"
                            }
                        ],
                        "status": 1
                    },
                    "logs": [
                        {
                            "logIndex": 0,
                            "transactionIndex": 0,
                            "transactionHash": "0x9ce67ba6f90a7017e3cf425fb3c76b7eec353e7908c089cbccdcd22ec89b3036",
                            "blockHash": "0x4f55beca03cb5ce8964e09adc1ba064392a62152687f98d79cb7960d2d6dde87",
                            "blockNumber": 20,
                            "address": "0xf204a4ef082f5c04bb89f7d5e6568b796096735a",
                            "type": "mined",
                            "event": "ItemDelisted",
                            "args": {
                                "itemAddress": "0x10271f4b537610009e1daf06779b9a8fde5ff531",
                                "name": "0x536869656c6400000000000000000000"
                            }
                        }
                    ]
                }
            }


            
## Group Lootbox

## Get Chances [/v1/lootbox/chances]

Get lootbox chances

### Get Chances [GET]

+ Response 200 (application/json)

        {
            "status": 200,
            "message": "Chances fetched",
            "data": [
                "1",
                "3",
                "30"
            ]
        }
        
## Get Items [/v1/lootbox/items/common]

Get lootbox items

### Get Items [GET]

+ Response 200 (application/json)

        {
            "status": 200,
            "message": "Items fetched",
            "data": [
                "0xc0c5def23634cfeb9f108b51371831e396e0eb90"
            ]
        }


## Get cost [/v1/lootbox/cost]

Get lootbox cost

### Get Cost [GET]

+ Response 200 (application/json)

        {
            "status": 200,
            "message": "Cost fetched",
            "data": 1
        }

## Update Cost [/v1/lootbox/cost/343]

Update Lootbox Cost

### Update Cost [GET]

+ Response 200 (application/json)

        
        {
            "status": 200,
            "message": "Updated lootbox cost",
            "data": {
                "tx": "0x1e8855dad37a92a0df89f9b9d4729095103cd70bdfd43504054994e79d309be0",
                "receipt": {
                    "transactionHash": "0x1e8855dad37a92a0df89f9b9d4729095103cd70bdfd43504054994e79d309be0",
                    "transactionIndex": 0,
                    "blockHash": "0xa66a1ff79e86053fd165b9b556e83b1176e768d3a4606f17722fee0d493cfc3b",
                    "blockNumber": 16,
                    "gasUsed": 43821,
                    "cumulativeGasUsed": 43821,
                    "contractAddress": null,
                    "logs": [
                        {
                            "logIndex": 0,
                            "transactionIndex": 0,
                            "transactionHash": "0x1e8855dad37a92a0df89f9b9d4729095103cd70bdfd43504054994e79d309be0",
                            "blockHash": "0xa66a1ff79e86053fd165b9b556e83b1176e768d3a4606f17722fee0d493cfc3b",
                            "blockNumber": 16,
                            "address": "0x30753e4a8aad7f8597332e813735def5dd395028",
                            "data": "0x0000000000000000000000000000000000000000000000000000000000000157",
                            "topics": [
                                "0xf8eb04e6c43013770ed5585d21a0eb9e40c228e8a53ccf549dc6cbdb8e50f67b"
                            ],
                            "type": "mined"
                        }
                    ],
                    "status": 1
                },
                "logs": [
                    {
                        "logIndex": 0,
                        "transactionIndex": 0,
                        "transactionHash": "0x1e8855dad37a92a0df89f9b9d4729095103cd70bdfd43504054994e79d309be0",
                        "blockHash": "0xa66a1ff79e86053fd165b9b556e83b1176e768d3a4606f17722fee0d493cfc3b",
                        "blockNumber": 16,
                        "address": "0x30753e4a8aad7f8597332e813735def5dd395028",
                        "type": "mined",
                        "event": "CostUpdated",
                        "args": {
                            "cost": "343"
                        }
                    }
                ]
            }
        }
        
        
## Update Chances [/v1/lootbox/chances/update/1/3/30]

Update chances of getting loot by rarity (epic, rare, uncommon)

### Update Chances [GET]

+ Response 200 (application/json)

        
        {
            "status": 200,
            "message": "Updated lootbox cost",
            "data": {
                "tx": "0x1e8855dad37a92a0df89f9b9d4729095103cd70bdfd43504054994e79d309be0",
                "receipt": {
                    "transactionHash": "0x1e8855dad37a92a0df89f9b9d4729095103cd70bdfd43504054994e79d309be0",
                    "transactionIndex": 0,
                    "blockHash": "0xa66a1ff79e86053fd165b9b556e83b1176e768d3a4606f17722fee0d493cfc3b",
                    "blockNumber": 16,
                    "gasUsed": 43821,
                    "cumulativeGasUsed": 43821,
                    "contractAddress": null,
                    "logs": [
                        {
                            "logIndex": 0,
                            "transactionIndex": 0,
                            "transactionHash": "0x1e8855dad37a92a0df89f9b9d4729095103cd70bdfd43504054994e79d309be0",
                            "blockHash": "0xa66a1ff79e86053fd165b9b556e83b1176e768d3a4606f17722fee0d493cfc3b",
                            "blockNumber": 16,
                            "address": "0x30753e4a8aad7f8597332e813735def5dd395028",
                            "data": "0x0000000000000000000000000000000000000000000000000000000000000157",
                            "topics": [
                                "0xf8eb04e6c43013770ed5585d21a0eb9e40c228e8a53ccf549dc6cbdb8e50f67b"
                            ],
                            "type": "mined"
                        }
                    ],
                    "status": 1
                },
                "logs": [
                    {
                        "logIndex": 0,
                        "transactionIndex": 0,
                        "transactionHash": "0x1e8855dad37a92a0df89f9b9d4729095103cd70bdfd43504054994e79d309be0",
                        "blockHash": "0xa66a1ff79e86053fd165b9b556e83b1176e768d3a4606f17722fee0d493cfc3b",
                        "blockNumber": 16,
                        "address": "0x30753e4a8aad7f8597332e813735def5dd395028",
                        "type": "mined",
                        "event": "CostUpdated",
                        "args": {
                            "cost": "343"
                        }
                    }
                ]
            }
        }

## New Lootbox Item [/v1/lootbox/item/add]

Add a new item to the loot table by rarity

### New Lootbox Item [POST]

+ Request (application/json)

    + Headers
        
            key: pWpzWuxoKUKAmlHc0wPi7lFS38FTth
            otp: ccccccglcrcdfbvrelclvcgjbbkkjtkhcvdbnlljlgke
    
    + Body

            {
                "item": "0xc0c5def23634cfeb9f108b51371831e396e0eb90",
                "rarity": "common"
            }


+ Response 200 (application/json)

        
        {
            "status": 200,
            "message": "New item added to loot table.",
            "data": {
                "tx": "0x48f0d7be6f6ff3452a916f3813454cba11ce596640bcb1253bfa9799cd2d0812",
                "receipt": {
                    "transactionHash": "0x48f0d7be6f6ff3452a916f3813454cba11ce596640bcb1253bfa9799cd2d0812",
                    "transactionIndex": 0,
                    "blockHash": "0xac31e289664c9c8a0596384ca34b5830475798b41931417c9e7396f33a894fc3",
                    "blockNumber": 14,
                    "gasUsed": 69892,
                    "cumulativeGasUsed": 69892,
                    "contractAddress": null,
                    "logs": [
                        {
                            "logIndex": 0,
                            "transactionIndex": 0,
                            "transactionHash": "0x48f0d7be6f6ff3452a916f3813454cba11ce596640bcb1253bfa9799cd2d0812",
                            "blockHash": "0xac31e289664c9c8a0596384ca34b5830475798b41931417c9e7396f33a894fc3",
                            "blockNumber": 14,
                            "address": "0x30753e4a8aad7f8597332e813735def5dd395028",
                            "data": "0x000000000000000000000000c0c5def23634cfeb9f108b51371831e396e0eb90",
                            "topics": [
                                "0xbb4ccd24eed82a7a2e60176fb55061c57af70aba4003ca2617491c7504a45ef5"
                            ],
                            "type": "mined"
                        }
                    ],
                    "status": 1
                },
                "logs": [
                    {
                        "logIndex": 0,
                        "transactionIndex": 0,
                        "transactionHash": "0x48f0d7be6f6ff3452a916f3813454cba11ce596640bcb1253bfa9799cd2d0812",
                        "blockHash": "0xac31e289664c9c8a0596384ca34b5830475798b41931417c9e7396f33a894fc3",
                        "blockNumber": 14,
                        "address": "0x30753e4a8aad7f8597332e813735def5dd395028",
                        "type": "mined",
                        "event": "LootBoxItemAdded",
                        "args": {
                            "item": "0xc0c5def23634cfeb9f108b51371831e396e0eb90"
                        }
                    }
                ]
            }
        }
        
        
## Group Token

## Get balance [/v1/token/balance/0x0]

Get address balance

### Get Balance [GET]

+ Response 200 (application/json)

        {
            "status": 200,
            "message": "Balance fetched",
            "data": 1
        }
        
## Get vault balance [/v1/token/vault/balance]

Get vault balance

### Get Vault Balance [GET]

+ Response 200 (application/json)

        {
            "status": 200,
            "message": "Vault balance fetched",
            "data": 1
        }
