module.exports = {
  getTokenAddress: require('./LootSafe/getTokenAddress'),
  newItem: require('./LootSafe/newItem'),
  getItems: require('./LootSafe/getItems'),
  getItem: require('./LootSafe/getItem'),
  spawnItem: require('./LootSafe/spawnItem'),
  clearAvailability: require('./LootSafe/clearAvailability'),
  issueTokens: require('./LootSafe/issueTokens'),
  getItemAddresses: require('./LootSafe/getItemAddresses'),
  // Crafter
  newRecipie: require('./Crafter/newRecipie'),
  newDeconstructionRecipie: require('./Crafter/newDeconstructionRecipie'),
  getRecipie: require('./Crafter/getRecipie'),
  getCraftables: require('./Crafter/getCraftables'),
  getDeconstrucatbles: require('./Crafter/getCraftables'),
  getDeconstructionRecipie: require('./Crafter/getDeconstructionRecipie'),
  removeRecipie: require('./Crafter/removeRecipie'),
  // LootBox
  addItem: require('./LootBox/addItem'),
  getChances: require('./LootBox/getChances'),
  getLootBoxItems: require('./LootBox/getLootBoxItems'),
  updateChance: require('./LootBox/updateChance'),
  updateLootBoxCost: require('./LootBox/updateLootBoxCost'),
  getLootBoxCost: require('./LootBox/getLootBoxCost'),
  // Token
  balanceOf: require('./Token/balanceOf'),
  getVaultBalance: require('./Token/getVaultBalance'),
  // Trade
  getTrade: require('./Trade/getTrade'),
  getTradeCost: require('./Trade/getTradeCost'),
  getTrades: require('./Trade/getTrades'),
  updateTradeCost: require('./Trade/updateTradeCost'),
  // Events
  fetchEvents: require('./Event/fetchEvents')
}